[meta]
name="micha"
email="michavardy@gmail.com"
git-remote="FROMFILE"

[project]
name="test_1"
directory='~/projects/customers/test_1'
deployment = ['deployment-client-1']

[deployment-client-1]
name="okteto"
type="ssh"
username=""
passphrase=""
ip=""

[interpreter]
path=""
venvExist=false
venvPath=""

[logging]
conf=""

[mapping]
[[mapping.keyValuePairs]]
local="/path/to/project/dir"
remote="/path/to/project/dir"
[[mapping.keyValuePairs]]
local="/path/to/sub_dir"
remote="/path/to/sub_dir"

[run_conf]

[debug]
