[meta]
name="micha"
email="micha.vardy@tufin.com"
git-remote="FROMFILE"

[project]
name="t-mobile"
directory='~/projects/customers/t-mobile'
deployment.name="okteto"
deployment.client.name="ssh"
deployment.client.credentials.username=""
deployment.client.credentials.passphrase=""
deployment.client.ip=""
deployment.mapping={}
interpreter.path=""
interpreter.venvExist=false
interpreter.venvPath=""
logger.conf=""

